# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 15:30
from __future__ import unicode_literals

from django.db import migrations


def create_initial_products(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')

    Product(name='Burger', description='Burger ot skarata s pileshko file', price=4.20).save()
    Product(name='Princesa', description='Princesa s kaima ot lelichkite', price=1.80).save()
    Product(name='Rizoto', description='Rizoto s oriz ot Fiori', price=5).save()
    Product(name='Pica', description='Pica pepperoni ot Dominos', price=12).save()
    Product(name='Gyros', description='Gyros ot Gyroland', price=3.50).save()
    Product(name='Diuner', description='Diuner s pileshko ot Alexa', price=3).save()
    Product(name='Kiufteta', description='Kiufteta na skara porciq ot Elias', price=5.40).save()
    Product(name='Spageti', description='Spageti Karbonara ot Raia', price=5.20).save()


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_products),
    ]
